#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

# Syntax:
#   <module name or kernel tree path, Unix shell pattern> <flag>[,<flag>...]
#
# Flags:
#   initramfs  - load module on initramfs
#   vendor     - module is a vendor module (default)
#   system     - module is a system module
#   recovery   - include module in recovery image
#   norecovery - do not include module in recovery image
#   load       - explicitly load the module
#   noload     - do not explicitly load the module

# All modules are copied to vendor by default

# Load all modules on initramfs, yolo
* location=initramfs,recovery=true,load=true

# Defer loading modules that requires firmware
drivers/bluetooth/* location=vendor
drivers/comedi/* location=vendor
drivers/gnss/* location=vendor
drivers/gpu/drm/* location=vendor
drivers/hid/* location=vendor
drivers/iio/* location=vendor
drivers/input/* location=vendor
drivers/leds/* location=vendor
drivers/media/* location=vendor
drivers/net/can/* location=vendor
drivers/net/ethernet/* location=vendor
drivers/net/wireless/* location=vendor
drivers/nfc/* location=vendor
drivers/rtc/* location=vendor
net/bluetooth/* location=vendor
net/can/* location=vendor
net/ethernet/* location=vendor
net/mac80211/* location=vendor
net/nfc/* location=vendor
net/wireless/* location=vendor
sound/* location=vendor

# Deferring Ethernet drivers needs us to do this
bnx2i.ko location=vendor
chcr.ko location=vendor
cxgb3i.ko location=vendor
cxgb4i.ko location=vendor
iw_cxgb4.ko location=vendor
libcxgbi.ko location=vendor
mlx4_ib.ko location=vendor
mlx5-vfio-pci.ko location=vendor
ocrdma.ko location=vendor

# Deferring input drivers needs us to do this
acer-wmi.ko location=vendor
asus-laptop.ko location=vendor
asus-nb-wmi.ko location=vendor
asus-wmi.ko location=vendor
cros_ec_ishtp.ko location=vendor
dell-laptop.ko location=vendor
dell-wmi.ko location=vendor
dell-wmi-aio.ko location=vendor
eeepc-laptop.ko location=vendor
eeepc-wmi.ko location=vendor
fujitsu-laptop.ko location=vendor
hp-wmi.ko location=vendor
huawei-wmi.ko location=vendor
ideapad-laptop.ko location=vendor
intel-hid.ko location=vendor
intel-vbtn.ko location=vendor
lg-laptop.ko location=vendor
msi-laptop.ko location=vendor
msi-wmi.ko location=vendor
panasonic-laptop.ko location=vendor
thinkpad_acpi.ko location=vendor
topstar-laptop.ko location=vendor
toshiba-wmi.ko location=vendor
toshiba_acpi.ko location=vendor

# Exclude vkms
vgem.ko location=none,recovery=false,load=false
vkms.ko location=none,recovery=false,load=false

# zram module is a system module
zram.ko location=system,recovery=false,load=true
zsmalloc.ko location=system,recovery=false,load=false
